#ifndef EXCEPTIONS_H
# define EXCEPTIONS_H

# define ONE			"Карта должна иметь расширение .cub!"
# define TWO			"Не удалось открыть файл!"
# define THREE			"Недостаточно параметров в файле!"
# define FOUR			"В файле присутствуют повторяющиеся параметры!"
# define FIVE			"Карта должна находиться в конце файла!"
# define SIX			"Задан некорректный размер экрана!"
# define SEVEN			"Слишком маленькая карта!"
# define EIGHT			"Ошибка выделения памяти для карты!"
# define NINE			"Карта должна быть окружена стенами!"
# define TEN			"Карта имеет недопустимые символы!!"
# define ELEVEN			"Неверное кол-во персонажей на карте!"
# define TWELVE			"Ошибка при инициализации окна!"
# define THIRTEEN		"Текстура не найдена!"
# define FOURTEEN		"Ошибка при вызове mlx_get_data_addr!"
# define FIFTEEN		"Неверный формат цвета! \
	Шаблон формата: R,G,B и могут быть разделены пробелами"
# define SIXTEEN		"Не удалось выделить память для spr_crds!"
# define SEVENTEEN		"Не удалось выделить память для sprite_order!"
# define EIGHTEEN		"Не удалось выделить память для sprite.distance!"
# define NINETEEN		"Не удалось выделить память для строки в GNL!"
# define TWENTY			"Не удалось выделить память для .....bmp!"
# define TWENTYONE		"Не удалось выделить память для строки в ft_add_spaces!"
# define TWENTYTWO		"Ошибка выделения памяти в init_cub!"
# define TWENTYTHREE	"Недопустимые символы в строке!"
# define TWENTYFOUR		"В конфиге присутствует несколько карт!"
# define TWENTYFIVE		"Символ не равный стене или пробелу \
	имеет рядом пробел!" 
# define TWENTYSIX		"Значение цвета не может быть больше 255!"
# define TWENTYSEVEN	"Значение цвета не может быть отрицательным!"
# define TWENTYEIGHT	"Неверные символы в строке цвета!"
# define TWENTYNINE		"После параметра должен следовать хотя бы один пробел!"
# define THIRTY			"В строке цвета присутствуют лишние символы!"
# define THIRTYONE		"Ошибка чтения информации из файла. \
	Возможно вы указали папку вместо файла!"
# define THIRTYTWO		"Ошибка выделения памяти под путь к файлу!"
# define THIRTYTHREE	"Файл имеет недопустимые параметры!"
# define THIRTYFOUR		"Параметр цвета имеет слишком большое значение!"
# define THIRTYFIVE		"Пустая строка после карты!"
# define THIRTYSIX		"Неправильно введеный третий параметр!"
# define THIRTYSEVEN	"Хей, слишком большие размеры для окна!"
# define THIRTYEIGHT	"Не удалось выделить память для структуры mlx!"
# define THIRTYNINE		"Не удалось выделить память для буффера!"
# define FORTY			"Вы не передали аргументы в программу!"

#endif